name: CI Deployment to AFaneca Server

on:
  push:
    branches: [ master ]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Connecting to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_SSH_HOST }}
        username: ${{ secrets.SERVER_SSH_USERNAME }}
        key: ${{ secrets.SERVER_SECRET }}
        port: ${{ secrets.SERVER_SSH_PORT }}
        script: |
          ./update_afascore_api.sh
